import { createContext, useContext, useState } from 'react'

const LangContext = createContext(null)

// ════════════════════════════════════════════════════════
//  TRADUCTIONS COMPLÈTES — FR + EN
//  Pattern moderne : toutes les strings en un seul endroit,
//  zéro texte hardcodé dans les composants.
// ════════════════════════════════════════════════════════
export const TRANSLATIONS = {

  // ──────────────────────────────────────────────────────
  //  FRANÇAIS
  // ──────────────────────────────────────────────────────
  fr: {

    // ── Navigation ───────────────────────────────────────
    nav: {
      carpooling:   'Covoiturage',
      bus:          'Bus',
      train:        'Train',
      soon:         'BIENTÔT',
      propose:      'Proposer un trajet',
      login:        'Connexion',
      register:     'Inscription',
      logout:       'Déconnexion',
      messages:     'Messages',
      profile:      'Mon profil',
      myTrips:      'Mes trajets',
      alerts:       'Alertes & Favoris',
      admin:        'Administration',
      new:          'NOUVEAU',
    },

    // ── Page d'accueil ───────────────────────────────────
    hero: {
      title1:       'Voyagez malin',
      title2:       'au Cameroun —',
      title3:       'Simple, sûr, abordable.',
      dep:          'Départ',
      dest:         'Destination',
      today:        "Aujourd'hui",
      returnDate:   'Retour',
      passengers:   '1 passager',
      nPassengers:  (n) => `${n} passager${n > 1 ? 's' : ''}`,
      search:       'Rechercher',
      newBadge:     'BIENTÔT',
    },

    popular: {
      label:        '🔥 Populaires',
      title:        'Trajets les plus demandés',
      seeAll:       'Voir tout',
      perWeek:      'trajets/sem.',
      from:         'dès',
    },

    how: {
      label:  'Simple & rapide',
      title:  'Comment ça marche ?',
      steps: [
        { icon: '🔍', title: 'Cherchez',   desc: "Entrez votre ville de départ et destination. Trouvez un conducteur qui fait la même route." },
        { icon: '💬', title: 'Contactez',  desc: "Échangez avec le conducteur via notre messagerie. Confirmez l'heure et le lieu de rendez-vous." },
        { icon: '🚗', title: 'Voyagez',    desc: "Montez à bord, partagez les frais et voyagez confortablement à travers le Cameroun." },
      ],
    },

    stats: [
      { value: '50K+',    label: 'Membres actifs' },
      { value: '8K+',     label: 'Trajets/mois' },
      { value: '96%',     label: 'Satisfaction' },
      { value: '120M F',  label: 'Économisés' },
    ],

    reviews: {
      label: '💬 Témoignages',
      title: 'Ils nous font confiance',
      list: [
        { name: 'Amina N.',  avatar: 'A', trip: 'Douala → Yaoundé',   text: 'Trajet confortable, conducteur sérieux et ponctuel. Je refais le même trajet chaque semaine !' },
        { name: 'Paul E.',   avatar: 'P', trip: 'Bafoussam → Douala', text: 'Économies réelles comparé au bus. La voiture est propre, climatisée. Application très simple.' },
        { name: 'Marie F.',  avatar: 'M', trip: 'Yaoundé → Kribi',    text: "Parfait pour aller à la plage en week-end ! Moins cher et plus rapide qu'un taxi." },
      ],
    },

    cta: {
      badge:  '🚀 Rejoignez la communauté',
      title1: 'Vous partez bientôt ?',
      title2: 'Publiez votre trajet.',
      desc:   'Rentabilisez le carburant, rencontrez des voyageurs sympa et voyagez moins cher partout au Cameroun.',
      btn:    'Publier un trajet',
      learn:  'En savoir plus',
      next:   "Prochain départ : aujourd'hui",
    },

    // ── Recherche ─────────────────────────────────────────
    search: {
      title:             'Trouver un trajet',
      placeholder_from:  'Ville de départ',
      placeholder_to:    "Ville d'arrivée",
      date_label:        'Date',
      passengers_label:  'Passagers',
      btn:               'Rechercher',
      filters:           'Filtres',
      show_filters:      'Afficher les filtres',
      hide_filters:      'Masquer les filtres',
      sort:              'Trier par',
      sort_price:        'Prix',
      sort_departure:    'Départ',
      sort_duration:     'Durée',
      sort_rating:       'Note',
      max_price:         'Prix maximum',
      time_slot:         'Heure de départ',
      time_all:          'Toute la journée',
      time_morning:      'Matin (5h–12h)',
      time_afternoon:    'Après-midi (12h–18h)',
      time_evening:      'Soir (18h+)',
      prefs:             'Préférences',
      results:           (n) => `${n} trajet${n > 1 ? 's' : ''} disponible${n > 1 ? 's' : ''}`,
      no_results:        'Aucun trajet trouvé',
      no_results_sub:    "Essayez d'autres dates ou d'autres villes.",
      book:              'Réserver',
      contact_driver:    'Contacter le conducteur',
      seats_left:        (n) => `${n} place${n > 1 ? 's' : ''} restante${n > 1 ? 's' : ''}`,
      full:              'Complet',
      driver:            'Conducteur',
      vehicle:           'Véhicule',
      departure:         'Départ',
      arrival:           'Arrivée',
      duration:          'Durée estimée',
      direct:            'Direct',
      loading:           'Recherche en cours…',
      alert_save:        'Sauvegarder en favori',
      alert_create:      'Créer une alerte',
      no_result_title:   'Aucun trajet trouvé',
      no_result_desc:    (from, to) => from && to ? `Pas de trajet disponible entre ${from} et ${to} pour le moment.` : 'Aucun trajet ne correspond à votre recherche.',
      favorite_cta:      "Soyez notifié dès qu'un conducteur publie ce trajet",
      alert_cta:         'Avec dates et prix max pour un matching précis',
      publish_cta:       'Vous êtes conducteur ? Proposez ce trajet vous-même !',
      publish_btn:       '+ Publier un trajet',
      back_results:      'Retour aux résultats',
      save_fav:          'Sauvegarder en favori',
      create_alert:      "Créer une alerte",
      fav_saved:         'Favori enregistré !',
      alert_created:     'Alerte créée !',
      fav_success:       (from, to) => `Vous recevrez un email dès qu'un conducteur publie un trajet ${from} → ${to}.`,
      alert_success:     (from, to) => `Nous vous alerterons dès qu'un trajet ${from} → ${to} sera disponible.`,
      manage_alerts:     'Gérer mes alertes →',
      publish_ride:      '+ Publier un trajet',
      you_driver:        'Vous êtes conducteur ? Proposez ce trajet vous-même !',
      min_dep:           'Date min',
      max_date:          'Date max',
      max_price_fcfa:    'Prix max (FCFA)',
      dep_required:      'Sélectionnez un départ et une destination.',
    },

    // ── Publication ───────────────────────────────────────
    publish: {
      title:         'Publier un trajet',
      subtitle:      'Partagez votre itinéraire et rentabilisez votre voyage',
      from:          'Ville de départ',
      to:            "Ville d'arrivée",
      from_address:  'Adresse précise de départ',
      to_address:    "Adresse précise d'arrivée",
      date:          'Date de départ',
      time:          'Heure de départ',
      seats:         'Nombre de places disponibles',
      price:         'Prix par passager (FCFA)',
      price_suggest: 'Prix suggéré',
      message:       'Message aux passagers',
      message_ph:    'Infos utiles : point de rendez-vous exact, bagages acceptés…',
      prefs:         'Préférences',
      submit:        'Publier le trajet',
      submitting:    'Publication en cours…',
      success:       'Trajet publié avec succès ! 🎉',
      free_left:     (n) => `Il vous reste ${n} trajet${n > 1 ? 's' : ''} gratuit${n > 1 ? 's' : ''}`,
      pref_ac:       'Climatisé',
      pref_music:    'Musique ok',
      pref_pets:     'Animaux ok',
      pref_quiet:    'Silencieux',
      pref_nosmoke:  'Non-fumeur',
      pref_usb:      'Chargeur USB',
    },

    // ── Messagerie ────────────────────────────────────────
    messages: {
      title:           'Messages',
      no_convos:       'Aucune conversation',
      no_convos_sub:   'Vos échanges avec les conducteurs et passagers apparaîtront ici.',
      search_convos:   'Rechercher une conversation…',
      type_message:    'Écrire un message…',
      send:            'Envoyer',
      typing:          (name) => `${name} est en train d'écrire…`,
      you:             'Vous',
      yesterday:       'Hier',
      unread:          (n) => `${n} non lu${n > 1 ? 's' : ''}`,
      booking_status:  'Statut de la réservation',
      trip_details:    'Détails du trajet',
      hint:            'Shift + Entrée pour retour à la ligne · Entrée pour envoyer',
      empty_state:     'Sélectionnez une conversation',
      empty_state_sub: 'Choisissez une conversation dans la liste à gauche',
      new_msg:         'Nouveau message',
      mark_read:       'Marquer comme lu',
    },

    // ── Mes trajets ───────────────────────────────────────
    my_trips: {
      title:             'Mes trajets',
      tab_passenger:     'En tant que passager',
      tab_driver:        'En tant que conducteur',
      no_trips:          'Aucun trajet pour le moment',
      no_trips_pass:     "Vous n'avez pas encore réservé de trajet.",
      no_trips_driver:   "Vous n'avez pas encore publié de trajet.",
      find_trip:         'Trouver un trajet',
      publish_trip:      'Publier un trajet',
      status_pending:    'En attente',
      status_confirmed:  'Confirmée',
      status_cancelled:  'Annulée',
      status_completed:  'Terminée',
      status_inquiry:    'Contact',
      confirm_trip:      'Confirmer le trajet',
      cancel_booking:    'Annuler',
      leave_review:      'Laisser un avis',
      edit_trip:         'Modifier',
      booking_count:     (n) => `${n} réservation${n > 1 ? 's' : ''}`,
      earnings:          'Gains estimés',
      seats_booked:      'Places réservées',
      departure_in:      'Départ dans',
      departed:          'Parti',
      per_seat:          '/ place',
      after_commission:  'après commission',
      driver_info:       'Infos conducteur',
      trip_info:         'Infos trajet',
    },

    // ── Profil ────────────────────────────────────────────
    profile: {
      title:           'Mon profil',
      tab_info:        '👤 Informations',
      tab_wallet:      '💰 Portefeuille',
      tab_reviews:     '⭐ Avis',
      edit:            'Modifier',
      save:            'Enregistrer',
      cancel:          'Annuler',
      saving:          'Enregistrement…',
      saved:           'Profil mis à jour ✅',
      first_name:      'Prénom',
      last_name:       'Nom',
      email:           'Email',
      phone:           'Téléphone',
      phone_ph:        'Ex: +237 6XX XXX XXX',
      bio:             'Bio',
      bio_ph:          'Présentez-vous en quelques mots…',
      verified:        '✅ Vérifié',
      member_since:    'Membre depuis',
      no_phone:        'Non renseigné',
      no_bio:          'Aucune bio renseignée.',
      change_photo:    'Modifier la photo',
      remove_photo:    'Supprimer la photo',
      earnings:        'Gains conducteur',
      earnings_sub:    'après commission 10%',
      spent:           'Total dépensé',
      spent_sub:       'en tant que passager',
      trips_driver:    'Trajets conducteur',
      trips_passenger: 'Trajets passager',
      confirmed_only:  'réservations confirmées',
      wallet_info:     'Le paiement se fait directement à bord ou via Mobile Money.',
      no_reviews:      "Aucun avis pour l'instant",
      no_reviews_sub:  'Les avis apparaîtront ici après vos trajets',
      personal_info:   'Informations personnelles',
      wallet_about:    'À propos du portefeuille',
      wallet_desc:     'Le portefeuille affiche vos gains estimés (après commission de 10%) et vos dépenses. Le paiement se fait directement à bord ou via Mobile Money.',
    },

    // ── Alertes & Favoris ─────────────────────────────────
    alerts: {
      title:             'Alertes & Favoris',
      subtitle:          "Soyez notifié dès qu'un trajet correspond à vos critères",
      tab_alerts:        '🔔 Alertes',
      tab_favorites:     '⭐ Favoris',
      new_alert:         'Nouvelle alerte',
      add_favorite:      'Ajouter',
      active_alerts:     (n) => `${n} alerte${n !== 1 ? 's' : ''} active${n !== 1 ? 's' : ''}`,
      max_alerts:        '· max 5',
      all_dates:         'Toutes dates · Tous prix',
      notifications_on:  '🔔 Notifications activées',
      notifications_off: '🔕 Notifications désactivées',
      no_alerts:         'Aucune alerte',
      no_alerts_sub:     "Créez une alerte pour être notifié dès qu'un trajet correspond à vos critères",
      no_favorites:      'Aucun itinéraire favori',
      no_favorites_sub:  'Ajoutez vos trajets habituels pour être notifié à chaque nouvelle publication',
      added_at:          'Ajouté le',
      date_from:         'Date min',
      date_to:           'Date max',
      max_price:         'Prix max (FCFA)',
      seats_needed:      'Places souhaitées',
      create_btn:        "Créer l'alerte",
      save_btn:          'Sauvegarder',
      created:           '✅ Alerte créée !',
      fav_added:         '⭐ Favori ajouté !',
      deleted:           'Supprimé.',
      max_reached:       'Maximum 5 alertes actives autorisées.',
      confirm_dep:       'Confirmez votre itinéraire pour être notifié à chaque nouveau trajet.',
      confirm_alert:     "Définissez votre trajet pour recevoir une alerte dès qu'un conducteur publie.",
      success_fav:       (from, to) => `Vous recevrez un email dès qu'un conducteur publie un trajet ${from} → ${to}.`,
      success_alert:     (from, to) => `Nous vous alerterons par email dès qu'un trajet ${from} → ${to} sera disponible.`,
      manage:            'Gérer mes alertes →',
      dep_required:      'Veuillez sélectionner un départ et une destination.',
      back:              'Retour',
      cancel:            'Annuler',
      new_alert_title:   '🔔 Nouvelle alerte',
      fav_title:         '⭐ Sauvegarder en favori',
      save_fav:          'Sauvegarder en favori',
      notify_on_new:     "Soyez notifié dès qu'un conducteur publie ce trajet",
      precise_match:     'Avec dates et prix max pour un matching précis',
    },

    // ── Authentification ──────────────────────────────────
    auth: {
      loginTitle:    'Bon retour ! 👋',
      loginSub:      'Connectez-vous pour continuer',
      email:         'Adresse email',
      password:      'Mot de passe',
      forgotPwd:     'Mot de passe oublié ?',
      loginBtn:      'Se connecter',
      loggingIn:     'Connexion…',
      noAccount:     'Pas encore de compte ?',
      createAccount: 'Créer un compte',
      orWith:        'Ou continuer avec',
      registerTitle: 'Créer un compte',
      alreadyHave:   'Déjà un compte ?',
      signIn:        'Se connecter',
      step_identity: 'Identité',
      step_access:   'Accès',
      step_profile:  'Profil',
      step_vehicle:  'Véhicule',
      first_name:    'Prénom',
      last_name:     'Nom',
      birth_date:    'Date de naissance',
      phone:         'Téléphone',
      phone_opt:     '(optionnel)',
      confirm_pwd:   'Confirmer le mot de passe',
      role_passenger:'Passager',
      role_driver:   'Conducteur',
      role_both:     'Les deux',
      role_label:    'Je souhaite…',
      bio_label:     'Bio',
      bio_opt:       '(optionnel)',
      bio_ph:        'Présentez-vous en quelques mots…',
      photo_label:   'Photo de profil',
      photo_opt:     '(optionnelle)',
      photo_click:   'Cliquez pour choisir une photo',
      photo_selected:'✅ Photo sélectionnée',
      terms_text:    'En créant un compte, vous acceptez nos',
      terms_link:    'CGU',
      privacy_link:  'politique de confidentialité',
      continue:      'Continuer →',
      back:          '← Retour',
      submit:        'Créer mon compte',
      submitting:    'Création…',
      pwd_weak:      'Faible',
      pwd_fair:      'Passable',
      pwd_good:      'Bien',
      pwd_strong:    'Fort',
      verify_title:  'Vérifiez votre email ! 📬',
      verify_sub:    (email) => `Un lien de confirmation a été envoyé à ${email}`,
      forgot_title:  'Mot de passe oublié',
      forgot_sub:    'Entrez votre email pour recevoir un lien de réinitialisation.',
      forgot_btn:    'Envoyer le lien',
      forgot_sent:   '✅ Email envoyé ! Vérifiez votre boîte.',
      reset_title:   'Nouveau mot de passe',
      reset_btn:     'Réinitialiser',
      reset_success: '✅ Mot de passe réinitialisé ! Vous pouvez vous connecter.',
      pwd_min:       'Minimum 8 caractères',
      pwd_match:     'Les mots de passe ne correspondent pas.',
      required_all:  'Veuillez remplir tous les champs obligatoires.',
    },

    // ── Réservation ───────────────────────────────────────
    booking: {
      confirm_title:    'Confirmer la réservation',
      seats:            'Nombre de places',
      message_ph:       'Message au conducteur (optionnel)',
      book_btn:         'Réserver →',
      booking_btn:      'Réservation en cours…',
      booked:           '✅ Réservation envoyée au conducteur !',
      already_booked:   '✅ Déjà réservé',
      contact_btn:      'Contacter',
      status_pending:   'En attente de confirmation',
      status_confirmed: 'Réservation confirmée',
      status_cancelled: 'Réservation annulée',
      accept:           'Accepter',
      decline:          'Refuser',
      confirm_driver:   'Confirmer le trajet',
      dispute:          'Signaler un problème',
    },

    // ── Avis ──────────────────────────────────────────────
    reviews_page: {
      title:        'Laisser un avis',
      subtitle:     (name) => `Comment s'est passé votre trajet avec ${name} ?`,
      rating_label: 'Note',
      comment_label:'Commentaire',
      comment_ph:   'Partagez votre expérience (optionnel)…',
      submit:       "Publier l'avis",
      submitting:   'Publication…',
      star_labels:  ['Très mauvais', 'Mauvais', 'Passable', 'Bien', 'Excellent !'],
    },

    // ── Contact ───────────────────────────────────────────
    contact: {
      title:         'Contactez-nous',
      subtitle:      'Une question ? Un problème ? Notre équipe est là.',
      subject_label: 'Sujet',
      email_label:   'Votre email',
      message_label: 'Votre message',
      submit:        'Envoyer le message',
      submitting:    'Envoi…',
      success:       '✅ Message envoyé ! Nous vous répondrons sous 24h.',
      urgency:       'Urgence : appelez le 117',
      faq_title:     'Questions fréquentes',
    },

    // ── Notifications ─────────────────────────────────────
    notifs: {
      no_notifs:         'Aucune notification',
      no_notifs_sub:     'Vos notifications apparaîtront ici.',
      new_booking:       'Nouvelle réservation',
      booking_confirmed: 'Réservation confirmée',
      booking_cancelled: 'Réservation annulée',
      new_message:       'Nouveau message',
      review_request:    'Donnez votre avis',
      trip_reminder:     'Rappel de départ',
      mark_all_read:     'Tout marquer comme lu',
      see_all:           'Voir toutes les notifications',
    },

    // ── Général ───────────────────────────────────────────
    misc: {
      trips:       'trajets disponibles',
      loading:     'Chargement…',
      book:        'Réserver',
      contact:     'Contacter',
      cancel:      'Annuler',
      send:        'Envoyer',
      back:        'Retour',
      confirm:     'Confirmer',
      save:        'Sauvegarder',
      delete:      'Supprimer',
      edit:        'Modifier',
      close:       'Fermer',
      next:        'Suivant',
      prev:        'Précédent',
      required:    'requis',
      optional:    'optionnel',
      or:          'ou',
      and:         'et',
      see_all:     'Voir tout',
      from:        'De',
      to:          'À',
      arrow:       '→',
      date:        'Date',
      hour:        'Heure',
      price:       'Prix',
      seats:       'Places',
      duration:    'Durée',
      direct:      'Direct',
      verified:    'Vérifié',
      reviews:     'avis',
      per_seat:    '/ place',
      per_person:  '/ personne',
      free:        'Gratuit',
      soon:        'Bientôt',
      new:         'Nouveau',
      error:       'Une erreur est survenue.',
      server_error:'Impossible de contacter le serveur.',
      copied:      'Copié !',
      share:       'Partager',
      km:          'km',
      fcfa:        'FCFA',
      min:         'min',
      h:           'h',
      departure:   'Départ',
      arrival:     'Arrivée',
      passenger:   'Passager',
      driver:      'Conducteur',
      trip:        'Trajet',
      enabled:     'Activé',
      disabled:    'Désactivé',
      enable:      'Activer',
      disable:     'Désactiver',
      add:         'Ajouter',
      create:      'Créer',
      update:      'Mettre à jour',
      submit:      'Envoyer',
      search:      'Rechercher',
      publish:     'Publier',
      login:       'Se connecter',
      logout:      'Déconnexion',
      register:    'S\'inscrire',
    },

    // ── Pied de page ──────────────────────────────────────
    footer: {
      tagline:   'Le covoiturage convivial et économique au Cameroun.',
      product:   'Produit',
      company:   'Entreprise',
      legal:     'Légal',
      links: {
        search:   'Trouver un trajet',
        publish:  'Publier un trajet',
        messages: 'Messages',
        alerts:   'Alertes',
        about:    'À propos',
        blog:     'Blog',
        press:    'Presse',
        careers:  'Carrières',
        terms:    'CGU',
        privacy:  'Confidentialité',
        cookies:  'Cookies',
      },
      copyright: (y) => `© ${y} Clando. Tous droits réservés.`,
    },

    // ── Erreurs ───────────────────────────────────────────
    errors: {
      not_found:       'Page introuvable',
      not_found_sub:   "La page que vous cherchez n'existe pas.",
      go_home:         "Retour à l'accueil",
      unauthorized:    'Vous devez être connecté pour accéder à cette page.',
      forbidden:       'Accès refusé.',
      blocked:         'Votre compte est suspendu.',
      blocked_sub:     "Contactez le support pour plus d'informations.",
      session_expired: 'Session expirée. Reconnectez-vous.',
      network:         'Erreur réseau. Vérifiez votre connexion.',
    },

    // ── Conducteur / Documents ────────────────────────────
    driver: {
      title:           'Espace conducteur',
      vehicle:         'Mon véhicule',
      docs:            'Documents',
      brand:           'Marque',
      model:           'Modèle',
      year:            'Année',
      color:           'Couleur',
      plate:           'Immatriculation',
      seats:           'Nombre de places',
      ac:              'Climatisation',
      doc_license:     'Permis de conduire',
      doc_insurance:   'Assurance véhicule',
      doc_status:      'Statut documents',
      pending_review:  'En cours de vérification',
      verified:        'Vérifié ✅',
      rejected:        'Refusé — rechargez vos documents',
      not_submitted:   'Non soumis',
      upload:          'Télécharger',
      re_upload:       'Remplacer',
      save:            'Enregistrer le véhicule',
      saving:          'Enregistrement…',
      saved:           '✅ Véhicule enregistré !',
      max_size:        'Max 5 Mo — JPG, PNG, PDF',
    },

    // ── Freemium ──────────────────────────────────────────
    freemium: {
      title:          'Compte freemium',
      free_trips:     (n) => `${n} trajets gratuits`,
      free_left:      (n) => `Il vous reste ${n} trajet${n !== 1 ? 's' : ''} gratuit${n !== 1 ? 's' : ''}`,
      blocked_title:  'Limite atteinte',
      blocked_sub:    'Vous avez utilisé vos 10 trajets gratuits. Réglez la commission pour continuer à publier.',
      commission:     'Commission à régler',
      pay_mtn:        'Payer via MTN MoMo',
      pay_orange:     'Payer via Orange Money',
      coming_soon:    'BIENTÔT',
      manual_steps:   'Comment payer manuellement',
      declare_paid:   'Déclarer mon paiement',
      or:             'ou',
    },

    // ── Admin ─────────────────────────────────────────────
    admin: {
      dashboard:      'Tableau de bord',
      users:          'Utilisateurs',
      trips:          'Trajets',
      bookings:       'Réservations',
      contacts:       'Support',
      debtors:        'Débiteurs',
      stats:          'Statistiques',
      total_users:    'Utilisateurs totaux',
      total_trips:    'Trajets publiés',
      total_bookings: 'Réservations',
      revenue:        'Revenus estimés',
      active_users:   'Actifs ce mois',
      search:         'Rechercher…',
      actions:        'Actions',
      ban:            'Suspendre',
      unban:          'Réactiver',
      delete:         'Supprimer',
      confirm_delete: 'Confirmer la suppression ?',
      role_admin:     'Admin',
      role_user:      'Utilisateur',
      verified:       'Vérifié',
      not_verified:   'Non vérifié',
      active:         'Actif',
      suspended:      'Suspendu',
    },
  },

  // ──────────────────────────────────────────────────────
  //  ENGLISH
  // ──────────────────────────────────────────────────────
  en: {

    nav: {
      carpooling:   'Carpooling',
      bus:          'Bus',
      train:        'Train',
      soon:         'SOON',
      propose:      'Offer a ride',
      login:        'Log in',
      register:     'Sign up',
      logout:       'Log out',
      messages:     'Messages',
      profile:      'My profile',
      myTrips:      'My rides',
      alerts:       'Alerts & Favourites',
      admin:        'Administration',
      new:          'NEW',
    },

    hero: {
      title1:       'Travel smart',
      title2:       'across Cameroon —',
      title3:       'Simple, safe, affordable.',
      dep:          'From',
      dest:         'To',
      today:        'Today',
      returnDate:   'Return',
      passengers:   '1 passenger',
      nPassengers:  (n) => `${n} passenger${n > 1 ? 's' : ''}`,
      search:       'Search',
      newBadge:     'COMING SOON',
    },

    popular: {
      label:   '🔥 Popular',
      title:   'Most popular routes',
      seeAll:  'See all',
      perWeek: 'rides/week',
      from:    'from',
    },

    how: {
      label: 'Simple & fast',
      title: 'How does it work?',
      steps: [
        { icon: '🔍', title: 'Search',   desc: 'Enter your departure city and destination. Find a driver on the same route.' },
        { icon: '💬', title: 'Connect',  desc: 'Chat with the driver through our secure messaging. Confirm the meetup time and place.' },
        { icon: '🚗', title: 'Travel',   desc: 'Hop in, share the costs and travel comfortably across Cameroon.' },
      ],
    },

    stats: [
      { value: '50K+',   label: 'Active members' },
      { value: '8K+',    label: 'Rides/month' },
      { value: '96%',    label: 'Satisfaction' },
      { value: '120M F', label: 'Saved' },
    ],

    reviews: {
      label: '💬 Testimonials',
      title: 'They trust us',
      list: [
        { name: 'Amina N.',  avatar: 'A', trip: 'Douala → Yaoundé',   text: 'Comfortable ride, serious and punctual driver. I take the same trip every week!' },
        { name: 'Paul E.',   avatar: 'P', trip: 'Bafoussam → Douala', text: 'Real savings compared to the bus. Clean, air-conditioned car. Very easy app.' },
        { name: 'Marie F.',  avatar: 'M', trip: 'Yaoundé → Kribi',    text: 'Perfect for a beach weekend! Cheaper and faster than a city taxi.' },
      ],
    },

    cta: {
      badge:  '🚀 Join the community',
      title1: 'Heading somewhere soon?',
      title2: 'Offer a ride.',
      desc:   'Cover your fuel costs, meet great people and travel cheaper across Cameroon.',
      btn:    'Offer a ride',
      learn:  'Learn more',
      next:   'Next departure: today',
    },

    search: {
      title:             'Find a ride',
      placeholder_from:  'Departure city',
      placeholder_to:    'Destination city',
      date_label:        'Date',
      passengers_label:  'Passengers',
      btn:               'Search',
      filters:           'Filters',
      show_filters:      'Show filters',
      hide_filters:      'Hide filters',
      sort:              'Sort by',
      sort_price:        'Price',
      sort_departure:    'Departure',
      sort_duration:     'Duration',
      sort_rating:       'Rating',
      max_price:         'Maximum price',
      time_slot:         'Departure time',
      time_all:          'All day',
      time_morning:      'Morning (5am–12pm)',
      time_afternoon:    'Afternoon (12pm–6pm)',
      time_evening:      'Evening (6pm+)',
      prefs:             'Preferences',
      results:           (n) => `${n} ride${n > 1 ? 's' : ''} available`,
      no_results:        'No rides found',
      no_results_sub:    'Try different dates or cities.',
      book:              'Book',
      contact_driver:    'Contact driver',
      seats_left:        (n) => `${n} seat${n > 1 ? 's' : ''} left`,
      full:              'Full',
      driver:            'Driver',
      vehicle:           'Vehicle',
      departure:         'Departure',
      arrival:           'Arrival',
      duration:          'Estimated duration',
      direct:            'Direct',
      loading:           'Searching…',
      alert_save:        'Save as favourite',
      alert_create:      'Create an alert',
      no_result_title:   'No rides found',
      no_result_desc:    (from, to) => from && to ? `No rides available between ${from} and ${to} right now.` : 'No rides match your search.',
      favorite_cta:      'Get notified when a driver posts this route',
      alert_cta:         'Set dates and max price for precise matching',
      publish_cta:       'Are you a driver? Post this ride yourself!',
      publish_btn:       '+ Post a ride',
      back_results:      'Back to results',
      save_fav:          'Save as favourite',
      create_alert:      'Create an alert',
      fav_saved:         'Favourite saved!',
      alert_created:     'Alert created!',
      fav_success:       (from, to) => `You'll get an email when a driver posts a ${from} → ${to} ride.`,
      alert_success:     (from, to) => `We'll alert you when a ${from} → ${to} ride becomes available.`,
      manage_alerts:     'Manage my alerts →',
      publish_ride:      '+ Post a ride',
      you_driver:        'Are you a driver? Post this ride yourself!',
      min_dep:           'From date',
      max_date:          'To date',
      max_price_fcfa:    'Max price (FCFA)',
      dep_required:      'Please select a departure and destination.',
    },

    publish: {
      title:         'Post a ride',
      subtitle:      'Share your route and make your trip more affordable',
      from:          'Departure city',
      to:            'Destination city',
      from_address:  'Exact pickup address',
      to_address:    'Exact drop-off address',
      date:          'Departure date',
      time:          'Departure time',
      seats:         'Available seats',
      price:         'Price per passenger (FCFA)',
      price_suggest: 'Suggested price',
      message:       'Message to passengers',
      message_ph:    'Useful info: exact meeting point, luggage policy…',
      prefs:         'Preferences',
      submit:        'Post ride',
      submitting:    'Posting…',
      success:       'Ride posted successfully! 🎉',
      free_left:     (n) => `You have ${n} free ride${n > 1 ? 's' : ''} left`,
      pref_ac:       'Air conditioning',
      pref_music:    'Music ok',
      pref_pets:     'Pets ok',
      pref_quiet:    'Quiet',
      pref_nosmoke:  'Non-smoker',
      pref_usb:      'USB charger',
    },

    messages: {
      title:           'Messages',
      no_convos:       'No conversations',
      no_convos_sub:   'Your chats with drivers and passengers will appear here.',
      search_convos:   'Search conversations…',
      type_message:    'Write a message…',
      send:            'Send',
      typing:          (name) => `${name} is typing…`,
      you:             'You',
      yesterday:       'Yesterday',
      unread:          (n) => `${n} unread`,
      booking_status:  'Booking status',
      trip_details:    'Ride details',
      hint:            'Shift + Enter for new line · Enter to send',
      empty_state:     'Select a conversation',
      empty_state_sub: 'Choose a conversation from the list on the left',
      new_msg:         'New message',
      mark_read:       'Mark as read',
    },

    my_trips: {
      title:             'My rides',
      tab_passenger:     'As passenger',
      tab_driver:        'As driver',
      no_trips:          'No rides yet',
      no_trips_pass:     "You haven't booked any rides yet.",
      no_trips_driver:   "You haven't posted any rides yet.",
      find_trip:         'Find a ride',
      publish_trip:      'Post a ride',
      status_pending:    'Pending',
      status_confirmed:  'Confirmed',
      status_cancelled:  'Cancelled',
      status_completed:  'Completed',
      status_inquiry:    'Inquiry',
      confirm_trip:      'Confirm ride',
      cancel_booking:    'Cancel',
      leave_review:      'Leave a review',
      edit_trip:         'Edit',
      booking_count:     (n) => `${n} booking${n > 1 ? 's' : ''}`,
      earnings:          'Estimated earnings',
      seats_booked:      'Seats booked',
      departure_in:      'Departing in',
      departed:          'Departed',
      per_seat:          '/ seat',
      after_commission:  'after commission',
      driver_info:       'Driver info',
      trip_info:         'Ride info',
    },

    profile: {
      title:           'My profile',
      tab_info:        '👤 Information',
      tab_wallet:      '💰 Wallet',
      tab_reviews:     '⭐ Reviews',
      edit:            'Edit',
      save:            'Save',
      cancel:          'Cancel',
      saving:          'Saving…',
      saved:           'Profile updated ✅',
      first_name:      'First name',
      last_name:       'Last name',
      email:           'Email',
      phone:           'Phone',
      phone_ph:        'e.g. +237 6XX XXX XXX',
      bio:             'Bio',
      bio_ph:          'Tell us a bit about yourself…',
      verified:        '✅ Verified',
      member_since:    'Member since',
      no_phone:        'Not provided',
      no_bio:          'No bio yet.',
      change_photo:    'Change photo',
      remove_photo:    'Remove photo',
      earnings:        'Driver earnings',
      earnings_sub:    'after 10% commission',
      spent:           'Total spent',
      spent_sub:       'as a passenger',
      trips_driver:    'Rides as driver',
      trips_passenger: 'Rides as passenger',
      confirmed_only:  'confirmed bookings',
      wallet_info:     'Payment is made directly on board or via Mobile Money.',
      no_reviews:      'No reviews yet',
      no_reviews_sub:  'Reviews will appear here after your rides',
      personal_info:   'Personal information',
      wallet_about:    'About the wallet',
      wallet_desc:     'The wallet shows your estimated earnings (after 10% commission) and your spending. Payments are made on board or via Mobile Money.',
    },

    alerts: {
      title:             'Alerts & Favourites',
      subtitle:          'Get notified when a ride matches your criteria',
      tab_alerts:        '🔔 Alerts',
      tab_favorites:     '⭐ Favourites',
      new_alert:         'New alert',
      add_favorite:      'Add',
      active_alerts:     (n) => `${n} active alert${n !== 1 ? 's' : ''}`,
      max_alerts:        '· max 5',
      all_dates:         'All dates · All prices',
      notifications_on:  '🔔 Notifications on',
      notifications_off: '🔕 Notifications off',
      no_alerts:         'No alerts',
      no_alerts_sub:     'Create an alert to be notified when a ride matches your criteria',
      no_favorites:      'No favourite routes',
      no_favorites_sub:  'Add your regular routes to be notified of new rides',
      added_at:          'Added on',
      date_from:         'From date',
      date_to:           'To date',
      max_price:         'Max price (FCFA)',
      seats_needed:      'Seats needed',
      create_btn:        'Create alert',
      save_btn:          'Save',
      created:           '✅ Alert created!',
      fav_added:         '⭐ Favourite saved!',
      deleted:           'Deleted.',
      max_reached:       'Maximum 5 active alerts allowed.',
      confirm_dep:       'Confirm your route to be notified of every new ride.',
      confirm_alert:     'Set your route to receive an alert when a driver posts.',
      success_fav:       (from, to) => `You'll get an email when a driver posts a ${from} → ${to} ride.`,
      success_alert:     (from, to) => `We'll alert you when a ${from} → ${to} ride becomes available.`,
      manage:            'Manage my alerts →',
      dep_required:      'Please select a departure and destination.',
      back:              'Back',
      cancel:            'Cancel',
      new_alert_title:   '🔔 New alert',
      fav_title:         '⭐ Save as favourite',
      save_fav:          'Save as favourite',
      notify_on_new:     'Get notified when a driver posts this route',
      precise_match:     'Set dates and max price for precise matching',
    },

    auth: {
      loginTitle:    'Welcome back! 👋',
      loginSub:      'Log in to continue',
      email:         'Email address',
      password:      'Password',
      forgotPwd:     'Forgot password?',
      loginBtn:      'Log in',
      loggingIn:     'Logging in…',
      noAccount:     'No account yet?',
      createAccount: 'Create an account',
      orWith:        'Or continue with',
      registerTitle: 'Create an account',
      alreadyHave:   'Already have an account?',
      signIn:        'Log in',
      step_identity: 'Identity',
      step_access:   'Access',
      step_profile:  'Profile',
      step_vehicle:  'Vehicle',
      first_name:    'First name',
      last_name:     'Last name',
      birth_date:    'Date of birth',
      phone:         'Phone',
      phone_opt:     '(optional)',
      confirm_pwd:   'Confirm password',
      role_passenger:'Passenger',
      role_driver:   'Driver',
      role_both:     'Both',
      role_label:    'I want to…',
      bio_label:     'Bio',
      bio_opt:       '(optional)',
      bio_ph:        'Tell us a bit about yourself…',
      photo_label:   'Profile photo',
      photo_opt:     '(optional)',
      photo_click:   'Click to choose a photo',
      photo_selected:'✅ Photo selected',
      terms_text:    'By creating an account, you agree to our',
      terms_link:    'Terms',
      privacy_link:  'Privacy Policy',
      continue:      'Continue →',
      back:          '← Back',
      submit:        'Create account',
      submitting:    'Creating…',
      pwd_weak:      'Weak',
      pwd_fair:      'Fair',
      pwd_good:      'Good',
      pwd_strong:    'Strong',
      verify_title:  'Check your email! 📬',
      verify_sub:    (email) => `A confirmation link was sent to ${email}`,
      forgot_title:  'Forgot password',
      forgot_sub:    'Enter your email to receive a reset link.',
      forgot_btn:    'Send link',
      forgot_sent:   '✅ Email sent! Check your inbox.',
      reset_title:   'New password',
      reset_btn:     'Reset password',
      reset_success: '✅ Password reset! You can now log in.',
      pwd_min:       'Minimum 8 characters',
      pwd_match:     "Passwords don't match.",
      required_all:  'Please fill in all required fields.',
    },

    booking: {
      confirm_title:    'Confirm booking',
      seats:            'Number of seats',
      message_ph:       'Message to driver (optional)',
      book_btn:         'Book →',
      booking_btn:      'Booking…',
      booked:           '✅ Booking sent to driver!',
      already_booked:   '✅ Already booked',
      contact_btn:      'Contact',
      status_pending:   'Awaiting confirmation',
      status_confirmed: 'Booking confirmed',
      status_cancelled: 'Booking cancelled',
      accept:           'Accept',
      decline:          'Decline',
      confirm_driver:   'Confirm ride',
      dispute:          'Report an issue',
    },

    reviews_page: {
      title:        'Leave a review',
      subtitle:     (name) => `How was your ride with ${name}?`,
      rating_label: 'Rating',
      comment_label:'Comment',
      comment_ph:   'Share your experience (optional)…',
      submit:       'Post review',
      submitting:   'Posting…',
      star_labels:  ['Very bad', 'Bad', 'OK', 'Good', 'Excellent!'],
    },

    contact: {
      title:         'Contact us',
      subtitle:      'A question? A problem? Our team is here.',
      subject_label: 'Subject',
      email_label:   'Your email',
      message_label: 'Your message',
      submit:        'Send message',
      submitting:    'Sending…',
      success:       "✅ Message sent! We'll reply within 24h.",
      urgency:       'Emergency: call 117',
      faq_title:     'Frequently asked questions',
    },

    notifs: {
      no_notifs:         'No notifications',
      no_notifs_sub:     'Your notifications will appear here.',
      new_booking:       'New booking',
      booking_confirmed: 'Booking confirmed',
      booking_cancelled: 'Booking cancelled',
      new_message:       'New message',
      review_request:    'Leave a review',
      trip_reminder:     'Departure reminder',
      mark_all_read:     'Mark all as read',
      see_all:           'See all notifications',
    },

    misc: {
      trips:       'rides available',
      loading:     'Loading…',
      book:        'Book',
      contact:     'Contact',
      cancel:      'Cancel',
      send:        'Send',
      back:        'Back',
      confirm:     'Confirm',
      save:        'Save',
      delete:      'Delete',
      edit:        'Edit',
      close:       'Close',
      next:        'Next',
      prev:        'Previous',
      required:    'required',
      optional:    'optional',
      or:          'or',
      and:         'and',
      see_all:     'See all',
      from:        'From',
      to:          'To',
      arrow:       '→',
      date:        'Date',
      hour:        'Time',
      price:       'Price',
      seats:       'Seats',
      duration:    'Duration',
      direct:      'Direct',
      verified:    'Verified',
      reviews:     'reviews',
      per_seat:    '/ seat',
      per_person:  '/ person',
      free:        'Free',
      soon:        'Soon',
      new:         'New',
      error:       'An error occurred.',
      server_error:'Unable to reach the server.',
      copied:      'Copied!',
      share:       'Share',
      km:          'km',
      fcfa:        'FCFA',
      min:         'min',
      h:           'h',
      departure:   'Departure',
      arrival:     'Arrival',
      passenger:   'Passenger',
      driver:      'Driver',
      trip:        'Ride',
      enabled:     'Enabled',
      disabled:    'Disabled',
      enable:      'Enable',
      disable:     'Disable',
      add:         'Add',
      create:      'Create',
      update:      'Update',
      submit:      'Submit',
      search:      'Search',
      publish:     'Post',
      login:       'Log in',
      logout:      'Log out',
      register:    'Sign up',
    },

    footer: {
      tagline:   'Friendly and affordable carpooling in Cameroon.',
      product:   'Product',
      company:   'Company',
      legal:     'Legal',
      links: {
        search:   'Find a ride',
        publish:  'Offer a ride',
        messages: 'Messages',
        alerts:   'Alerts',
        about:    'About',
        blog:     'Blog',
        press:    'Press',
        careers:  'Careers',
        terms:    'Terms',
        privacy:  'Privacy',
        cookies:  'Cookies',
      },
      copyright: (y) => `© ${y} Clando. All rights reserved.`,
    },

    errors: {
      not_found:       'Page not found',
      not_found_sub:   "The page you're looking for doesn't exist.",
      go_home:         'Back to home',
      unauthorized:    'You must be logged in to access this page.',
      forbidden:       'Access denied.',
      blocked:         'Your account is suspended.',
      blocked_sub:     'Contact support for more information.',
      session_expired: 'Session expired. Please log in again.',
      network:         'Network error. Check your connection.',
    },

    driver: {
      title:           'Driver space',
      vehicle:         'My vehicle',
      docs:            'Documents',
      brand:           'Brand',
      model:           'Model',
      year:            'Year',
      color:           'Colour',
      plate:           'Plate number',
      seats:           'Seats',
      ac:              'Air conditioning',
      doc_license:     "Driver's licence",
      doc_insurance:   'Vehicle insurance',
      doc_status:      'Document status',
      pending_review:  'Under review',
      verified:        'Verified ✅',
      rejected:        'Rejected — please re-upload',
      not_submitted:   'Not submitted',
      upload:          'Upload',
      re_upload:       'Replace',
      save:            'Save vehicle',
      saving:          'Saving…',
      saved:           '✅ Vehicle saved!',
      max_size:        'Max 5 MB — JPG, PNG, PDF',
    },

    freemium: {
      title:          'Freemium account',
      free_trips:     (n) => `${n} free rides`,
      free_left:      (n) => `You have ${n} free ride${n !== 1 ? 's' : ''} left`,
      blocked_title:  'Limit reached',
      blocked_sub:    'You have used your 10 free rides. Pay the commission to keep posting.',
      commission:     'Commission to pay',
      pay_mtn:        'Pay via MTN MoMo',
      pay_orange:     'Pay via Orange Money',
      coming_soon:    'COMING SOON',
      manual_steps:   'How to pay manually',
      declare_paid:   'Declare my payment',
      or:             'or',
    },

    admin: {
      dashboard:      'Dashboard',
      users:          'Users',
      trips:          'Rides',
      bookings:       'Bookings',
      contacts:       'Support',
      debtors:        'Debtors',
      stats:          'Statistics',
      total_users:    'Total users',
      total_trips:    'Rides posted',
      total_bookings: 'Bookings',
      revenue:        'Estimated revenue',
      active_users:   'Active this month',
      search:         'Search…',
      actions:        'Actions',
      ban:            'Suspend',
      unban:          'Reactivate',
      delete:         'Delete',
      confirm_delete: 'Confirm deletion?',
      role_admin:     'Admin',
      role_user:      'User',
      verified:       'Verified',
      not_verified:   'Not verified',
      active:         'Active',
      suspended:      'Suspended',
    },
  },
}

// ── Provider ──────────────────────────────────────────────────
export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() =>
    localStorage.getItem('cvg_lang') || 'en'   // anglais par défaut
  )

  // Synchroniser avec la langue du compte (appelé par AuthContext après login)
  const setLangAndSave = (l) => {
    if (!TRANSLATIONS[l]) return
    setLangState(l)
    localStorage.setItem('cvg_lang', l)
  }

  const toggleLang = () => {
    setLangAndSave(lang === 'fr' ? 'en' : 'fr')
  }

  const t = TRANSLATIONS[lang] || TRANSLATIONS['en']

  return (
    <LangContext.Provider value={{ lang, toggleLang, setLang: setLangAndSave, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
